openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /definitions/:
    get:
      operationId: listDictionarys
      description: ''
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: word
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=4
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=2
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Dictionary'
          description: ''
      tags:
      - definitions
  /definitions/{rowid}/:
    get:
      operationId: retrieveDictionary
      description: ''
      parameters:
      - name: rowid
        in: path
        required: true
        description: A unique value identifying this dictionary.
        schema:
          type: string
      - name: word
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dictionary'
          description: ''
      tags:
      - definitions
  /thesaurus/:
    get:
      operationId: listThesaurusEntrys
      description: ''
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: word
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=4
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=2
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/ThesaurusEntry'
          description: ''
      tags:
      - thesaurus
  /thesaurus/{rowid}/:
    get:
      operationId: retrieveThesaurusEntry
      description: ''
      parameters:
      - name: rowid
        in: path
        required: true
        description: A unique value identifying this thesaurus entry.
        schema:
          type: string
      - name: word
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThesaurusEntry'
          description: ''
      tags:
      - thesaurus
components:
  schemas:
    Dictionary:
      type: object
      properties:
        part-of-speech:
          type: string
          maxLength: 1
        word:
          type: string
          maxLength: 128
        definition:
          type: string
      required:
      - part-of-speech
      - word
      - definition
    ThesaurusEntry:
      type: object
      properties:
        part-of-speech:
          type: string
          maxLength: 4
        word:
          type: string
          maxLength: 128
        synonyms:
          type: array
          items:
            type: string
        antonyms:
          type: array
          items:
            type: string
      required:
      - part-of-speech
      - word
      - synonyms
      - antonyms
